export const ASSET_LOADER_COMPLETION = 'ASSET_LOADER_COMPLETION';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const REQUEST_AUTHORIZATION = 'REQUEST_AUTHORIZATION';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';

export const REQUEST_ACCOUNT_CREATION = 'REQUEST_ACCOUNT_CREATION';
export const ACCOUNT_CREATION_SUCCESS = 'ACCOUNT_CREATION_SUCCESS';
export const ACCOUNT_CREATION_FAILED = 'ACCOUNT_CREATION_FAILED';

