export const NOOP = 'NOOP';

export const ASSET_LOADER_COMPLETION = 'ASSET_LOADER_COMPLETION';

export const WINDOW_RESIZE_EVENT_RECEIVED = 'WINDOW_RESIZE_EVENT_RECEIVED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const REQUEST_AUTH = 'REQUEST_AUTH';

export const LOGIN_FAILED = 'LOGIN_FAILED';